---
# Ansible Role: Update
exclude_enabled: false
yum_dnf_exclude: 'exclude=kernel*, docker*, kube*'
update_state: 'latest'

# Ansible Role: Firewalld
enable_firewalld: true

# Ansible Role: Utilities
install_system_utilities: true
install_tar: true
install_zip: true
install_vim: true
install_nano: true
install_htop: true
install_nfs_utils: false

# Ansible Role: Development Tools
install_development_tools: true

# Ansible Role: Swap
swap_enabled: true
swap_files:
  - /swap
  - /swapfile
  - /swap.img
swap_size: '4096'
swap_file_path: /swapfile
swappiness_value: 10
vfs_cache_pressure_value: 50

# Ansible Role: Reboot
pre_reboot_delay: 5
post_reboot_delay: 30